[package]
name = "mzdeisotope"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mz-averagine"
path = "src/averagine.rs"


[dependencies]

num-traits = "0.2"

mzdata = { path = "../mzdata/" }
mzpeaks = { version = "0.7.0" }
mzsignal = { version = "0.3.1", default-features = false, optional = true}
chemical_elements = { path = "../chemical-elements/", features=['mzpeaks']}

[dev-dependencies]
flate2 = "1.0.28"
