[workspace]

resolver = "2"

members = [
    "mzdeisotope",
    "mzdeisotope-map",
    "mzdeisotoper"
]

[workspace.dependencies]

mzdata = { version = ">=0.23.0", default-features = false, features = ["mzsignal", "nalgebra"] }
mzpeaks = { version = ">=0.17.0,<1.0.0" }

[profile.release]
lto = true
codegen-units = 1
opt-level = 2
debug = true

[patch.crates-io]