set dotenv-load := true

test:
    cargo t

alias t := test

docs:
    cargo doc --lib --no-deps

docmath:
    cargo clean --doc
    RUSTDOCFLAGS="--html-in-header mzdeisotope/doc/katex.html" cargo doc --lib --no-deps -v