[package]
name = "mzdeisotoper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
mzdeisotope = { path = "../mzdeisotope" }
# mzdata = { version = "0.7.0", features = ["mzsignal", "nalgebra"]}
mzdata = { path = "../../mzdata", features = ["mzsignal", "nalgebra"]}
mzpeaks = { version = "0.8.0" }
log = "0.4.20"
itertools = "0.12.0"
rayon = "1.7.0"
flate2 = "1.0.28"
pretty_env_logger = "0.5.0"
clap = { version = "4.4.11", features = ["derive"]}


[dev-dependencies]
